### ISSUE TITLE
uneble to login

### ISSUE THREAD

**Issue by josephmazigo** [rythe77/odoo11_android#1]
Hi get this error when i try to login

V/: LoginUser()
V/: LoginProcess
    Processing Self Hosted Server Login
I/System.out: port:8069
I/rba23.toserba2: The ClassLoaderContext is a special shared library.
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
V/: Testing URL :http://192.168.1.10:8069
I/System.out: port:8069
W/System.err: de.timroes.axmlrpc.XMLRPCServerException: Traceback (most recent call last):
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\wsgi_server.py", line 124, in wsgi_xmlrpc
        result = odoo.http.dispatch_rpc(service, method, params)
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 118, in dispatch_rpc
        result = dispatch(method, params)
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\common.py", line 57, in dispatch
W/System.err:     return g[exp_method_name](*params)
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\common.py", line 30, in exp_authenticate
        return res_users.authenticate(db, login, password, user_agent_env)
      File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\res\res_users.py", line 496, in authenticate
        uid = cls._login(db, login, password)
      File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\res\res_users.py", line 474, in _login
        user.sudo(user_id).check_credentials(password)
      File "c:\users\user\appdata\local\openerp s.a\odoo\addons\11.0\login_user_detail\models\login_user_details.py", line 36, in check_credentials
        ip_address = request.httprequest.environ['REMOTE_ADDR']
      File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
        return getattr(self._get_current_object(), name)
      File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
        return self.__local()
      File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\local.py", line 135, in _lookup
        raise RuntimeError('object unbound')
    RuntimeError: object unbound
W/System.err:  [1]
        at de.timroes.axmlrpc.ResponseParser.parse(ResponseParser.java:78)
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:742)
W/System.err:     at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:462)
        at org.duckdns.toserba23.toserba23.utils.QueryUtils.makeXmlRpcRequest(QueryUtils.java:360)
        at org.duckdns.toserba23.toserba23.utils.QueryUtils.getUid(QueryUtils.java:106)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:42)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:12)
        at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:319)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:73)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:61)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
E/android.content.Context: Problem connecting server XML-RPC
    de.timroes.axmlrpc.XMLRPCServerException: Traceback (most recent call last):
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\wsgi_server.py", line 124, in wsgi_xmlrpc
        result = odoo.http.dispatch_rpc(service, method, params)
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\http.py", line 118, in dispatch_rpc
        result = dispatch(method, params)
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\common.py", line 57, in dispatch
        return g[exp_method_name](*params)
      File "C:\Program Files (x86)\Odoo 11.0\server\odoo\service\common.py", line 30, in exp_authenticate
        return res_users.authenticate(db, login, password, user_agent_env)
      File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\res\res_users.py", line 496, in authenticate
        uid = cls._login(db, login, password)
      File "c:\program files (x86)\odoo 11.0\server\odoo\addons\base\res\res_users.py", line 474, in _login
        user.sudo(user_id).check_credentials(password)
      File "c:\users\user\appdata\local\openerp s.a\odoo\addons\11.0\login_user_detail\models\login_user_details.py", line 36, in check_credentials
        ip_address = request.httprequest.environ['REMOTE_ADDR']
      File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
        return getattr(self._get_current_object(), name)
      File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\local.py", line 306, in _get_current_object
        return self.__local()
      File "C:\Program Files (x86)\Odoo 11.0\python\lib\site-packages\werkzeug\local.py", line 135, in _lookup
        raise RuntimeError('object unbound')
    RuntimeError: object unbound
     [1]
        at de.timroes.axmlrpc.ResponseParser.parse(ResponseParser.java:78)
        at de.timroes.axmlrpc.XMLRPCClient$Caller.call(XMLRPCClient.java:742)
        at de.timroes.axmlrpc.XMLRPCClient.call(XMLRPCClient.java:462)
        at org.duckdns.toserba23.toserba23.utils.QueryUtils.makeXmlRpcRequest(QueryUtils.java:360)
        at org.duckdns.toserba23.toserba23.utils.QueryUtils.getUid(QueryUtils.java:106)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:42)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:12)
        at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:319)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:73)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:61)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System.err: java.lang.NumberFormatException: For input string: ""
        at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.parseInt(Integer.java:650)
        at org.duckdns.toserba23.toserba23.utils.QueryUtils.getUid(QueryUtils.java:106)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:42)
W/System.err:     at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:12)
        at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:319)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:73)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:61)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
E/android.content.Context: Problem authenticating with server.
    java.lang.NumberFormatException: For input string: ""
        at java.lang.Integer.parseInt(Integer.java:627)
        at java.lang.Integer.parseInt(Integer.java:650)
        at org.duckdns.toserba23.toserba23.utils.QueryUtils.getUid(QueryUtils.java:106)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:42)
        at org.duckdns.toserba23.toserba23.loader.LoginLoader.loadInBackground(LoginLoader.java:12)
        at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:319)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:73)
        at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:61)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
I/AssistStructure: Flattened final assist data: 6104 bytes, containing 1 windows, 19 views
I/rba23.toserba2: The ClassLoaderContext is a special shared library.
I/System.out: [OkHttp] sendRequest>>
I/System.out: [OkHttp] sendRequest<<
V/android.content.Context: Json response from server: [""]
W/RenderThread: type=1400 audit(0.0:12577): avc: denied { search } for name="battery" dev="sysfs" ino=6954 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:sysfs_batteryinfo:s0 tclass=dir permissive=0

**Comment by CreatorB** [comment]
same here.

apa ada update terbaru mas @rythe77 ?

Terimakasih sebelumnya.
